# please enter the command for calling SAVAGE:
#  --> 'savage' if the tool was installed through bioconda
#  --> '/path/to/savage/dir/savage' when using the git repository
SAVAGE_EXE:
    '~/git_repos/savage/savage'

############# Input files #############

# Please enter the paths to your input fastq files
SINGLES_FILE: # enter empty string "" if absent
    "input_fas/singles.fastq"
PAIRED1_FILE: # enter empty string "" if absent
    "input_fas/paired1.fastq"
PAIRED2_FILE: # enter empty string "" if absent
    "input_fas/paired2.fastq"

############# Basic parameters #############

# Choose the mode in which you want to run SAVAGE: de novo or reference guided?
DE_NOVO:
    False # set to True for de novo mode, False for ad-hoc reference guided mode
REF: # fasta file containing reference genome; only used in reference guided mode
    "/home/jasmijn/git_repos/savage/example/hiv-ref.fasta" # enter absolute path

# Set the minimal overlap length
MIN_OVERLAP_LEN:
    200 # We recommend 60% of the average length of the input reads

# If the data set is of coverage > 1000x, we recommend to split the data into
# smaller subsets for error correction. After stage a the resulting contigs
# will be combined in stage b for the remaining stages of the algorithm.
# Choose this number such that total coverage/SPLIT_NUM is between 500x and 1000x
SPLIT_NUM:
    1 # IMPORTANT - don't forget to adjust this parameter to your data set!

# Set the number of threads allowed for parallel computations
NUM_THREADS:
    8
    
############# Advanced parameters #############

# Set a threshold for the mismatch rate allowed when building master strains (stage c)
MERGE_CONTIGS:
    0.0 # Default = 0.0

# Set a minimal contig length for stage c input; shorter contigs will be removed and ignored
CONTIG_LEN_STAGE_C:
    100 # Default = 100

# Set the minimal overlap length for building master strains (stage c)
OVERLAP_LEN_STAGE_C:
    100 # Default = 100

# Decide whether you want to allow merging along branching edges in stages b & c
# Not removing branches may lead to longer contigs, but if the diversity in the
# sample is too low, it will result in too many haplotypes (all possible combinations)
REMOVE_BRANCHES:
    1 # Default = 1 (recommended); set to 0 to allow merging along branching edges

# For diploid genomes, we offer a final merging round making use of the knowledge
# that there are only 2 haplotypes.
DIPLOID:
    1 # Default = 0; only set to 1 when the sample is known to be diploid (e.g. human)

    
############# Frequency estimation #############

# For frequency estimation we offer two modes; most accurate is Kallisto-mode,
# but this requires Kallisto to be installed (see the SAVAGE manual).
KALLISTO:
    0 # default = 1 (recommended); set to 0 if Kallisto is not installed
KALLISTO_PATH:
    "/home/jasmijn/Software/kallisto_linux-v0.43.0/kallisto" # only needed in kallisto-mode

# Choose the minimum contig length to be considered for frequency estimation
MIN_LEN_FREQ_EST:
    1000 # default = 1000

# Original read files (before merging self-overlapping reads with PEAR)
FORWARD:
    "~/git_repos/savage/example/input_fas/paired1.fastq" # only needed in kallisto-mode
REVERSE:
    "~/git_repos/savage/example/input_fas/paired2.fastq" # only needed in kallisto-mode
