# please enter the full path to the SAVAGE root directory
SAVAGE_DIR:
    '~/git_repos/private-savage'

# Choose the mode in which you want to run SAVAGE: de novo or reference guided?
DE_NOVO:
    True # set to True for de novo mode, False for ad-hoc reference guided mode
REF: # fasta file containing reference genome; only used in reference guided mode
    "/home/jasmijn/git_repos/private-savage/example_unmerged/test/test_ref.fasta"

MIN_OVERLAP_LEN:
    200
NUM_THREADS:
    4
MIN_LEN_FREQ_EST:
    1000

# Are you using single-end or paired-end reads? It is recommended not to use both.
SINGLE_END_READS:
    False # set to True for single-end reads, False for paired-end reads

# Please enter the paths (full or from the current directory) to your input fastq files
SINGLES_FILE: # enter empty string "" if absent
    "../input/singles.fastq"
PAIRED1_FILE: # enter empty string "" if absent
    "../input/forward.fastq"
PAIRED2_FILE: # enter empty string "" if absent
    "../input/reverse.fastq"

# Set a threshold for the mismatch rate allowed when building master strains (stage c)
MERGE_CONTIGS:
    0.01

# If the data set is of coverage > 1000x, we recommend to split the data into
# smaller subsets for error correction. After stage a the resulting contigs
# will be combined in stage b for the remaining stages of the algorithm.
# We provide a special Snakefile for this analysis; when using this Snakefile,
# make sure to set the parameter below.

# In how many patches do you want to split your data?
# Choose this number such that coverage/SPLIT_NUM is between 500x and 1000x
SPLIT_NUM:
    4
